let token=localStorage.getItem("w2e_token");
const $=id=>document.getElementById(id);
function showTab(t){$("login").classList.toggle("hidden",t!=="login");$("register").classList.toggle("hidden",t!=="register");}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...(token?{Authorization:"Bearer "+token}:{})};if(opt.body&&typeof opt.body!=="string"){opt.headers["Content-Type"]="application/json";opt.body=JSON.stringify(opt.body)}const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Something went wrong");return d}
$("login").onsubmit=async e=>{e.preventDefault();try{const d=await api("/api/login",{method:"POST",body:{login:$("l_login").value,password:$("l_pass").value}});localStorage.setItem("w2e_token",d.token);token=d.token;load()}catch(x){$("msg").textContent=x.message}};
$("register").onsubmit=async e=>{e.preventDefault();try{const d=await api("/api/register",{method:"POST",body:{username:$("r_user").value,mobile:$("r_mobile").value,email:$("r_email").value,password:$("r_pass").value,confirmPassword:$("r_confirm").value,referralCode:$("r_ref").value}});localStorage.setItem("w2e_token",d.token);token=d.token;load()}catch(x){$("msg").textContent=x.message}};
async function load(){try{const u=await api("/api/me");$("auth").classList.add("hidden");$("dash").classList.remove("hidden");$("username").textContent=u.username;$("refcode").textContent=u.referral_code;$("balance").textContent="৳"+u.balance;$("earned").textContent="৳"+u.total_earned;$("refs").textContent=u.referrals;const ts=await api("/api/tasks");$("tasks").innerHTML=ts.length?ts.map(t=>`<div class="task"><b>${escapeHtml(t.title)}</b><p>${escapeHtml(t.description)}</p><strong>Reward: ৳${t.reward}</strong><button onclick="submitTask(${t.id})" style="float:right">Submit Proof</button></div>`).join(""):"এখন কোনো task নেই।";}catch(e){logout()}}
async function submitTask(id){const proof=prompt("Proof / screenshot link দিন:");if(!proof)return;try{await api("/api/tasks/"+id+"/submit",{method:"POST",body:{proof}});alert("Proof submitted.");}catch(e){alert(e.message)}}
$("withdraw").onsubmit=async e=>{e.preventDefault();try{await api("/api/withdraw",{method:"POST",body:{method:$("method").value,account:$("account").value,amount:Number($("amount").value)}});alert("Withdrawal request submitted.");load()}catch(x){alert(x.message)}};
function logout(){localStorage.removeItem("w2e_token");location.reload()}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
$("theme").onclick=()=>{document.body.classList.toggle("light");$("theme").textContent=document.body.classList.contains("light")?"🌙 Dark":"☀️ Light"};
if(token)load();