const express=require('express');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const helmet=require('helmet');const rateLimit=require('express-rate-limit');const {Pool}=require('pg');
const app=express();const PORT=process.env.PORT||10000;const JWT_SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET_BEFORE_DEPLOYING';
app.use(helmet({crossOriginResourcePolicy:false}));app.use(express.json({limit:'15mb'}));app.use(express.urlencoded({extended:true,limit:'15mb'}));
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
const q=(s,p=[])=>pool.query(s,p);const clean=(v,n=5000)=>String(v??'').trim().slice(0,n);
function token(u){return jwt.sign({id:u.id,username:u.username},JWT_SECRET,{expiresIn:'30d'})}
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch{return res.status(401).json({error:'Login required'})}}
function adminAuth(req,res,next){const au=process.env.ADMIN_USERNAME||'admin',ap=process.env.ADMIN_PASSWORD||'';const h=req.headers.authorization||'';if(!h.startsWith('Basic '))return res.status(401).json({error:'Admin login required'});try{const d=Buffer.from(h.slice(6),'base64').toString(),i=d.indexOf(':');if(d.slice(0,i)!==au||!ap||d.slice(i+1)!==ap)throw 0;next()}catch{return res.status(401).json({error:'Invalid admin login'})}}
const limiter=rateLimit({windowMs:15*60*1000,max:100});
async function setting(k,f=''){const r=await q('SELECT value FROM settings WHERE key=$1',[k]);return r.rows[0]?.value??f}async function setSetting(k,v){await q('INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[k,String(v)])}
function code(u){return u.replace(/[^a-z0-9]/gi,'').slice(0,8).toUpperCase()+Math.random().toString(36).slice(2,7).toUpperCase()}
async function initDb(){
await q(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,username VARCHAR(50) UNIQUE NOT NULL,mobile VARCHAR(30) UNIQUE NOT NULL,email VARCHAR(150) UNIQUE NOT NULL,password_hash TEXT NOT NULL,referral_code VARCHAR(40) UNIQUE NOT NULL,referred_by INTEGER REFERENCES users(id),balance INTEGER NOT NULL DEFAULT 0,deposit_balance INTEGER NOT NULL DEFAULT 0,total_earned INTEGER NOT NULL DEFAULT 0,total_withdrawn INTEGER NOT NULL DEFAULT 0,total_deposited INTEGER NOT NULL DEFAULT 0,completed_tasks INTEGER NOT NULL DEFAULT 0,rejected_tasks INTEGER NOT NULL DEFAULT 0,banned BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
await q(`CREATE TABLE IF NOT EXISTS tasks(id SERIAL PRIMARY KEY,title VARCHAR(200) NOT NULL,description TEXT NOT NULL,reward INTEGER NOT NULL,max_participants INTEGER NOT NULL DEFAULT 2,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
await q(`CREATE TABLE IF NOT EXISTS submissions(id SERIAL PRIMARY KEY,task_id INTEGER NOT NULL REFERENCES tasks(id),user_id INTEGER NOT NULL REFERENCES users(id),proof TEXT NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'pending',rejection_reason TEXT,reviewed_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
await q(`CREATE TABLE IF NOT EXISTS withdrawals(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),method VARCHAR(30) NOT NULL,account VARCHAR(150) NOT NULL,amount INTEGER NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'pending',rejection_reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),reviewed_at TIMESTAMPTZ)`);
await q(`CREATE TABLE IF NOT EXISTS deposit_requests(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),method VARCHAR(30) NOT NULL,account VARCHAR(150) NOT NULL,amount INTEGER NOT NULL,transaction_id VARCHAR(150) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'pending',rejection_reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),reviewed_at TIMESTAMPTZ)`);
await q(`CREATE TABLE IF NOT EXISTS settings(key VARCHAR(100) PRIMARY KEY,value TEXT NOT NULL)`);
for(const x of ['ALTER TABLE users ADD COLUMN IF NOT EXISTS deposit_balance INTEGER NOT NULL DEFAULT 0','ALTER TABLE users ADD COLUMN IF NOT EXISTS total_deposited INTEGER NOT NULL DEFAULT 0','ALTER TABLE tasks ADD COLUMN IF NOT EXISTS max_participants INTEGER NOT NULL DEFAULT 2'])await q(x);
await q(`ALTER TABLE submissions ADD COLUMN IF NOT EXISTS rejection_reason TEXT`);await q(`ALTER TABLE submissions ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ`);await q(`ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS rejection_reason TEXT`);await q(`ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ`);await q(`ALTER TABLE deposit_requests ADD COLUMN IF NOT EXISTS rejection_reason TEXT`);await q(`ALTER TABLE deposit_requests ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ`);
await q(`CREATE UNIQUE INDEX IF NOT EXISTS one_active_submission_per_task_user ON submissions(task_id,user_id) WHERE status IN ('pending','approved')`);await q(`UPDATE tasks SET max_participants=2 WHERE max_participants IS NULL OR max_participants<2`);
const d={telegram:'',depositEnabled:'false',depositMinAmount:'50',depositBkashEnabled:'true',depositBkashNumber:'',depositNagadEnabled:'true',depositNagadNumber:'',depositBinanceEnabled:'false',depositBinanceAccount:'',depositInstructions:'Payment করার পর Transaction ID দিয়ে Verify করুন।'};for(const [k,v] of Object.entries(d))await q('INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO NOTHING',[k,v])}
app.post('/api/register',limiter,async(req,res)=>{try{const username=clean(req.body.username,50),mobile=clean(req.body.mobile,30),email=clean(req.body.email,150).toLowerCase(),password=String(req.body.password||''),confirm=String(req.body.confirmPassword||''),ref=clean(req.body.referralCode,40);if(!username||!mobile||!email||!password)return res.status(400).json({error:'সব required তথ্য দিন'});if(password.length<6)return res.status(400).json({error:'Password কমপক্ষে 6 characters হতে হবে'});if(password!==confirm)return res.status(400).json({error:'Password match করছে না'});if((await q('SELECT id FROM users WHERE username=$1 OR mobile=$2 OR email=$3',[username,mobile,email])).rows[0])return res.status(400).json({error:'Username/Mobile/Email আগে থেকেই আছে'});let referredBy=null;if(ref){const r=await q('SELECT id FROM users WHERE referral_code=$1',[ref]);if(!r.rows[0])return res.status(400).json({error:'Referral Code সঠিক নয়'});referredBy=r.rows[0].id}let rc=code(username);while((await q('SELECT id FROM users WHERE referral_code=$1',[rc])).rows[0])rc=code(username);const r=await q('INSERT INTO users(username,mobile,email,password_hash,referral_code,referred_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[username,mobile,email,await bcrypt.hash(password,10),rc,referredBy]);res.json({token:token(r.rows[0]),user:r.rows[0]})}catch(e){console.error(e);res.status(500).json({error:'Registration failed'})}});
app.post('/api/login',limiter,async(req,res)=>{try{const login=clean(req.body.login,150),password=String(req.body.password||''),r=await q('SELECT * FROM users WHERE username=$1 OR mobile=$1 OR email=$1 LIMIT 1',[login]),u=r.rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Login তথ্য সঠিক নয়'});if(u.banned)return res.status(403).json({error:'আপনার account banned'});res.json({token:token(u)})}catch(e){res.status(500).json({error:'Login failed'})}});
app.get('/api/me',auth,async(req,res)=>{try{const r=await q('SELECT id,username,mobile,email,referral_code,balance,deposit_balance,total_earned,total_withdrawn,total_deposited,completed_tasks,rejected_tasks,banned,created_at FROM users WHERE id=$1',[req.user.id]);if(!r.rows[0])return res.status(404).json({error:'User not found'});const x=await q('SELECT COUNT(*)::int count FROM users WHERE referred_by=$1',[req.user.id]);res.json({...r.rows[0],referrals:x.rows[0].count})}catch(e){res.status(500).json({error:'Profile load failed'})}});
app.get('/api/tasks',auth,async(req,res)=>{try{const r=await q(`SELECT t.*,COALESCE((SELECT COUNT(*) FROM submissions s WHERE s.task_id=t.id AND s.status='approved'),0)::int approved_participants,COALESCE((SELECT COUNT(*) FROM submissions s WHERE s.task_id=t.id AND s.status='pending'),0)::int pending_participants FROM tasks t WHERE t.active=TRUE ORDER BY t.id DESC`);res.json(r.rows)}catch(e){res.status(500).json({error:'Tasks load failed'})}});
app.post('/api/tasks/:id/submit',auth,async(req,res)=>{const c=await pool.connect();try{const id=Number(req.params.id),proof=clean(req.body.proof,120000);if(!Number.isInteger(id)||!proof)throw Error('Task/Proof সঠিক নয়');await c.query('BEGIN');const u=(await c.query('SELECT id,banned FROM users WHERE id=$1 FOR UPDATE',[req.user.id])).rows[0];if(!u||u.banned)throw Error('Account banned');const t=(await c.query('SELECT * FROM tasks WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!t||!t.active)throw Error('Task আর active নেই');if((await c.query(`SELECT id FROM submissions WHERE task_id=$1 AND user_id=$2 AND status IN ('pending','approved')`,[id,req.user.id])).rows[0])throw Error('এই task ইতিমধ্যে submit করেছেন');const n=(await c.query(`SELECT COUNT(*)::int count FROM submissions WHERE task_id=$1 AND status IN ('pending','approved')`,[id])).rows[0].count;if(n>=t.max_participants){await c.query('UPDATE tasks SET active=FALSE WHERE id=$1',[id]);throw Error('Task-এর participant limit পূর্ণ')}await c.query('INSERT INTO submissions(task_id,user_id,proof) VALUES($1,$2,$3)',[id,req.user.id,proof]);if(n+1>=t.max_participants)await c.query('UPDATE tasks SET active=FALSE WHERE id=$1',[id]);await c.query('COMMIT');res.json({ok:true,message:'Proof submitted'})}catch(e){await c.query('ROLLBACK').catch(()=>{});res.status(400).json({error:e.message})}finally{c.release()}});
app.post('/api/withdraw',auth,async(req,res)=>{const c=await pool.connect();try{const method=clean(req.body.method,30),account=clean(req.body.account,150),amount=Number(req.body.amount);if(!['bKash','Nagad','Binance'].includes(method)||!account||!Number.isInteger(amount)||amount<50)throw Error('Withdrawal তথ্য সঠিক নয় / Minimum ৳50');await c.query('BEGIN');const u=(await c.query('SELECT balance,banned FROM users WHERE id=$1 FOR UPDATE',[req.user.id])).rows[0];if(!u||u.banned)throw Error('Account banned');if(u.balance<amount)throw Error('Earned balance যথেষ্ট নয়');await c.query('UPDATE users SET balance=balance-$1 WHERE id=$2',[amount,req.user.id]);await c.query('INSERT INTO withdrawals(user_id,method,account,amount) VALUES($1,$2,$3,$4)',[req.user.id,method,account,amount]);await c.query('COMMIT');res.json({ok:true,message:'Withdrawal request submitted'})}catch(e){await c.query('ROLLBACK').catch(()=>{});res.status(400).json({error:e.message})}finally{c.release()}});
app.get('/api/withdrawals',auth,async(req,res)=>{try{res.json((await q('SELECT id,method,account,amount,status,rejection_reason,created_at,reviewed_at FROM withdrawals WHERE user_id=$1 ORDER BY id DESC',[req.user.id])).rows)}catch(e){res.status(500).json({error:'History failed'})}});
app.get('/api/deposit/settings',auth,async(req,res)=>{const ks=['depositEnabled','depositMinAmount','depositBkashEnabled','depositBkashNumber','depositNagadEnabled','depositNagadNumber','depositBinanceEnabled','depositBinanceAccount','depositInstructions'];const o={};for(const k of ks)o[k]=await setting(k,'');res.json(o)});
app.post('/api/deposit',auth,async(req,res)=>{try{if(await setting('depositEnabled','false')!=='true')return res.status(400).json({error:'Deposit এখন বন্ধ আছে'});const method=clean(req.body.method,30),account=clean(req.body.account,150),tx=clean(req.body.transactionId,150),amount=Number(req.body.amount),min=Number(await setting('depositMinAmount','50'));if(!['bKash','Nagad','Binance'].includes(method)||!account||!tx||!Number.isInteger(amount)||amount<min)return res.status(400).json({error:`Minimum deposit ৳${min}`});const key=method==='bKash'?'depositBkashEnabled':method==='Nagad'?'depositNagadEnabled':'depositBinanceEnabled';if(await setting(key,'false')!=='true')return res.status(400).json({error:'এই deposit method এখন বন্ধ আছে'});await q('INSERT INTO deposit_requests(user_id,method,account,amount,transaction_id) VALUES($1,$2,$3,$4,$5)',[req.user.id,method,account,amount,tx]);res.json({ok:true,message:'Deposit verification request submitted'})}catch(e){res.status(500).json({error:'Deposit request failed'})}});
app.get('/api/deposits',auth,async(req,res)=>{try{res.json((await q('SELECT id,method,account,amount,transaction_id,status,rejection_reason,created_at,reviewed_at FROM deposit_requests WHERE user_id=$1 ORDER BY id DESC',[req.user.id])).rows)}catch(e){res.status(500).json({error:'Deposit history failed'})}});
app.post('/api/admin/login',limiter,(req,res)=>{if(clean(req.body.username,100)===(process.env.ADMIN_USERNAME||'admin')&&String(req.body.password||'')===(process.env.ADMIN_PASSWORD||'')&&process.env.ADMIN_PASSWORD)return res.json({ok:true});res.status(401).json({error:'Invalid admin login'})});
app.get('/api/admin/stats',adminAuth,async(req,res)=>{try{const [a,b,c,d,e]=await Promise.all([q('SELECT COUNT(*)::int count FROM users'),q('SELECT COUNT(*)::int count FROM tasks WHERE active=TRUE'),q("SELECT COUNT(*)::int count FROM submissions WHERE status='pending'"),q("SELECT COUNT(*)::int count FROM withdrawals WHERE status='pending'"),q("SELECT COUNT(*)::int count FROM deposit_requests WHERE status='pending'")]);res.json({users:a.rows[0].count,activeTasks:b.rows[0].count,pendingProofs:c.rows[0].count,pendingWithdrawals:d.rows[0].count,pendingDeposits:e.rows[0].count})}catch(e){res.status(500).json({error:'Stats failed'})}});
app.get('/api/admin/users',adminAuth,async(req,res)=>{try{res.json((await q('SELECT id,username,mobile,email,referral_code,balance,deposit_balance,total_earned,total_withdrawn,total_deposited,completed_tasks,rejected_tasks,banned,created_at FROM users ORDER BY id DESC')).rows)}catch(e){res.status(500).json({error:'Users load failed'})}});
app.patch('/api/admin/users/:id/ban',adminAuth,async(req,res)=>{try{await q('UPDATE users SET banned=$1 WHERE id=$2',[Boolean(req.body.banned),Number(req.params.id)]);res.json({ok:true})}catch(e){res.status(500).json({error:'Ban update failed'})}});
app.get('/api/admin/tasks',adminAuth,async(req,res)=>{try{res.json((await q(`SELECT t.*,COALESCE((SELECT COUNT(*) FROM submissions s WHERE s.task_id=t.id AND s.status='approved'),0)::int approved_participants,COALESCE((SELECT COUNT(*) FROM submissions s WHERE s.task_id=t.id AND s.status='pending'),0)::int pending_participants FROM tasks t ORDER BY t.id DESC`)).rows)}catch(e){res.status(500).json({error:'Tasks load failed'})}});
app.post('/api/admin/tasks',adminAuth,async(req,res)=>{try{const title=clean(req.body.title,200),description=clean(req.body.description,10000),reward=Number(req.body.reward),max=Number(req.body.maxParticipants??2);if(!title||!description||!Number.isInteger(reward)||reward<5||!Number.isInteger(max)||max<2)return res.status(400).json({error:'Reward minimum ৳5 এবং participants minimum 2'});res.json((await q('INSERT INTO tasks(title,description,reward,max_participants) VALUES($1,$2,$3,$4) RETURNING *',[title,description,reward,max])).rows[0])}catch(e){res.status(500).json({error:'Task create failed'})}});
app.delete('/api/admin/tasks/:id',adminAuth,async(req,res)=>{try{const id=Number(req.params.id);if(!Number.isInteger(id))return res.status(400).json({error:'Task ID সঠিক নয়'});const r=await q('SELECT id,active FROM tasks WHERE id=$1',[id]);if(!r.rows[0])return res.status(404).json({error:'Task পাওয়া যায়নি'});await q('UPDATE tasks SET active=FALSE WHERE id=$1',[id]);res.json({ok:true,message:'Task deleted successfully'})}catch(e){res.status(500).json({error:'Task delete করা যায়নি'})}});
app.get('/api/admin/proofs',adminAuth,async(req,res)=>{try{res.json((await q(`SELECT s.*,u.username,u.mobile,t.title,t.reward,t.max_participants FROM submissions s JOIN users u ON u.id=s.user_id JOIN tasks t ON t.id=s.task_id ORDER BY s.id DESC`)).rows)}catch(e){res.status(500).json({error:'Proofs load failed'})}});
app.patch('/api/admin/proofs/:id',adminAuth,async(req,res)=>{const c=await pool.connect();try{const id=Number(req.params.id),status=clean(req.body.status,20),reason=clean(req.body.reason,2000);if(!['approved','rejected'].includes(status))throw Error('Review status সঠিক নয়');await c.query('BEGIN');const s=(await c.query('SELECT s.*,t.reward,t.max_participants FROM submissions s JOIN tasks t ON t.id=s.task_id WHERE s.id=$1 FOR UPDATE',[id])).rows[0];if(!s||s.status!=='pending')throw Error('Proof পাওয়া যায়নি বা already reviewed');if(status==='approved'){const n=(await c.query("SELECT COUNT(*)::int count FROM submissions WHERE task_id=$1 AND status='approved'",[s.task_id])).rows[0].count;if(n>=s.max_participants)throw Error('Participant limit পূর্ণ');const u=(await c.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[s.user_id])).rows[0];if(!u||u.banned)throw Error('User banned');await c.query("UPDATE submissions SET status='approved',reviewed_at=NOW() WHERE id=$1",[id]);await c.query('UPDATE users SET balance=balance+$1,total_earned=total_earned+$1,completed_tasks=completed_tasks+1 WHERE id=$2',[s.reward,s.user_id]);if(u.completed_tasks+1===20&&u.referred_by)await c.query('UPDATE users SET balance=balance+20,total_earned=total_earned+20 WHERE id=$1',[u.referred_by]);const after=(await c.query("SELECT COUNT(*)::int count FROM submissions WHERE task_id=$1 AND status='approved'",[s.task_id])).rows[0].count;if(after>=s.max_participants)await c.query('UPDATE tasks SET active=FALSE WHERE id=$1',[s.task_id])}else{await c.query("UPDATE submissions SET status='rejected',rejection_reason=$2,reviewed_at=NOW() WHERE id=$1",[id,reason||'Proof rejected']);await c.query('UPDATE users SET rejected_tasks=rejected_tasks+1 WHERE id=$1',[s.user_id]);await c.query("UPDATE tasks SET active=TRUE WHERE id=$1 AND active=FALSE AND (SELECT COUNT(*) FROM submissions WHERE task_id=$1 AND status='approved')<max_participants",[s.task_id])}await c.query('COMMIT');res.json({ok:true})}catch(e){await c.query('ROLLBACK').catch(()=>{});res.status(400).json({error:e.message})}finally{c.release()}});
app.get('/api/admin/withdrawals',adminAuth,async(req,res)=>{try{res.json((await q('SELECT w.*,u.username,u.mobile FROM withdrawals w JOIN users u ON u.id=w.user_id ORDER BY w.id DESC')).rows)}catch(e){res.status(500).json({error:'Withdrawals load failed'})}});
app.patch('/api/admin/withdrawals/:id',adminAuth,async(req,res)=>{const c=await pool.connect();try{const id=Number(req.params.id),status=clean(req.body.status,20),reason=clean(req.body.reason,2000);if(!['approved','rejected'].includes(status))throw Error('Status সঠিক নয়');await c.query('BEGIN');const w=(await c.query('SELECT * FROM withdrawals WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!w||w.status!=='pending')throw Error('Withdrawal পাওয়া যায়নি বা reviewed');if(status==='rejected')await c.query('UPDATE users SET balance=balance+$1 WHERE id=$2',[w.amount,w.user_id]);else await c.query('UPDATE users SET total_withdrawn=total_withdrawn+$1 WHERE id=$2',[w.amount,w.user_id]);await c.query('UPDATE withdrawals SET status=$1,rejection_reason=$2,reviewed_at=NOW() WHERE id=$3',[status,status==='rejected'?reason||'Withdrawal rejected':null,id]);await c.query('COMMIT');res.json({ok:true})}catch(e){await c.query('ROLLBACK').catch(()=>{});res.status(400).json({error:e.message})}finally{c.release()}});
app.get('/api/admin/deposit-settings',adminAuth,async(req,res)=>{const ks=['depositEnabled','depositMinAmount','depositBkashEnabled','depositBkashNumber','depositNagadEnabled','depositNagadNumber','depositBinanceEnabled','depositBinanceAccount','depositInstructions'];const o={};for(const k of ks)o[k]=await setting(k,'');res.json(o)});
app.patch('/api/admin/deposit-settings',adminAuth,async(req,res)=>{try{for(const k of ['depositEnabled','depositMinAmount','depositBkashEnabled','depositBkashNumber','depositNagadEnabled','depositNagadNumber','depositBinanceEnabled','depositBinanceAccount','depositInstructions'])if(req.body[k]!==undefined)await setSetting(k,clean(req.body[k],5000));res.json({ok:true})}catch(e){res.status(500).json({error:'Deposit settings update failed'})}});
app.get('/api/admin/deposits',adminAuth,async(req,res)=>{try{res.json((await q('SELECT d.*,u.username,u.mobile FROM deposit_requests d JOIN users u ON u.id=d.user_id ORDER BY d.id DESC')).rows)}catch(e){res.status(500).json({error:'Deposits load failed'})}});
app.patch('/api/admin/deposits/:id',adminAuth,async(req,res)=>{const c=await pool.connect();try{const id=Number(req.params.id),status=clean(req.body.status,20),reason=clean(req.body.reason,2000);if(!['approved','rejected'].includes(status))throw Error('Status সঠিক নয়');await c.query('BEGIN');const d=(await c.query('SELECT * FROM deposit_requests WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!d||d.status!=='pending')throw Error('Deposit request পাওয়া যায়নি বা reviewed');if(status==='approved')await c.query('UPDATE users SET deposit_balance=deposit_balance+$1,total_deposited=total_deposited+$1 WHERE id=$2',[d.amount,d.user_id]);await c.query('UPDATE deposit_requests SET status=$1,rejection_reason=$2,reviewed_at=NOW() WHERE id=$3',[status,status==='rejected'?reason||'Deposit rejected':null,id]);await c.query('COMMIT');res.json({ok:true})}catch(e){await c.query('ROLLBACK').catch(()=>{});res.status(400).json({error:e.message})}finally{c.release()}});
app.get('/api/settings',async(req,res)=>res.json({telegram:await setting('telegram',''),depositEnabled:await setting('depositEnabled','false')}));app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');res.json({ok:true,service:'Work2Earn BD'})}catch{res.status(500).json({ok:false})}});
app.use(express.static('.'));initDb().then(()=>app.listen(PORT,()=>console.log('Work2Earn BD running on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
